"""
Django settings for session project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from ast import literal_eval
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# ROOT_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
ENV_TYPE = config("ENV_TYPE", default="local")
DEBUG = ENV_TYPE != "prod"

ALLOWED_HOSTS = [h.strip() for h in config("ALLOWED_HOSTS", default="").split(",") if h.strip()]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_recaptcha',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'userauth',
    "django_celery_beat",
    "djcelery_email",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'userauth.throttles.RegisterIPThrottle',
        'userauth.throttles.VerifySessionThrottle',
        'userauth.throttles.LoginIPThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '1000/day',
        'verify_session': '100/minute',
        'two_factor_management': '10/minute',
        'two_factor_verify': '10/minute',
        'crypto_batch': '120/minute',
        'register': '2/minute',
        'login': '4/minute'
    },
    'NUM_PROXIES': None,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
]

if not DEBUG:
    MIDDLEWARE += ["whitenoise.middleware.WhiteNoiseMiddleware"]

MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'middleware.logmiddleware.RequestLoggingMiddleware',
    'middleware.reqmiddleware.RequestMiddleware',
    'middleware.adminmiddleware.AdminLoginBlockMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT'),
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

if not DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'userauth.User'

WALLET_DOMAIN = config("WALLET_DOMAIN", default="")
UI_DOMAIN = config("UI_DOMAIN", default="")
SESSION_DOMAIN = config("SESSION_DOMAIN", default="")
NEXT_UI_DOMAIN = config("NEXT_UI_DOMAIN", default="")
APP_PROTOCOL = config("APP_PROTOCOL", default="http")

PASSWORD_RESET_TIMEOUT = 120

CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

EMAIL_DOMAIN_ALLOWED_LIST = [h.strip() for h in config("EMAIL_DOMAIN_ALLOWED_LIST", default="").split(",") if h.strip()]
EMAIL_BACKEND = "djcelery_email.backends.CeleryEmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

CACHE_TIMEOUT = 6000

ADMIN_FAILURE_LIMIT = int(config("ADMIN_FAILURE_LIMIT"))

ADMIN_TEMPORARY_BLOCK_TIME = int(config("ADMIN_TEMPORARY_BLOCK_TIME"))
USER_TEMPORARY_BLOCK_TIME = int(config("USER_TEMPORARY_BLOCK_TIME"))

ADMIN_ALLOWED_IPS = config("ADMIN_ALLOWED_IPS", cast=literal_eval)
ALLOWED_WALLET_IPS = config("ALLOWED_WALLET_IPS", cast=literal_eval)

RECAPTCHA_PUBLIC_KEY = config("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = config("RECAPTCHA_PRIVATE_KEY")

ADMIN_PATH = config("ADMIN_PATH")

SERVER_SALT = config("SERVER_SALT")
VALID_HMAC = config("VALID_HMAC", default=1800, cast=int)

APP_AES_KEY = config("APP_AES_KEY")
APP_HMAC_KEY = config("APP_HMAC_KEY")

CELERY_BEAT_SCHEDULE = {
    'delete-old-temp-blocked-ips-daily': {
        'task': 'userauth.delete_old_temporary_blocked_ips',
        'schedule': crontab(hour='*/15'),
    },
    'delete_inactive_users_older_than_3_days-every-day': {
        'task': 'userauth.delete_inactive_users_older_than_3_days',
        'schedule': crontab(hour='*/24'),
    },
    'delete_invalid_sessions-every-day': {
        'task': 'userauth.delete_invalid_sessions',
        'schedule': crontab(hour='*/24'),
    },
}

AUTHENTICATION_BACKENDS = [
    'userauth.backends.UsernameOrEmailBackend',
    "django.contrib.auth.backends.ModelBackend",
]

# SESSION
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800

ENV_TYPE = config("ENV_TYPE", default="local")
LOG_TO_STDOUT = ENV_TYPE in {"prod", "test"}
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO" if ENV_TYPE == "prod" else "DEBUG")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.json.JsonFormatter',
            'format': '%(levelname)s %(name)-12s %(asctime)s %(module)s %(process)d %(thread)d %(channel)s %(message)s',
        },
    },
    "filters": {
        "ch_session": {
            "()": "config.logging_filters.ChannelFilter",
            "channel": "session-auth",
        },
        "ch_request": {
            "()": "config.logging_filters.ChannelFilter",
            "channel": "request",
        },
        "ch_admin": {
            "()": "config.logging_filters.ChannelFilter",
            "channel": "admin",
        },
        "ch_root": {
            "()": "config.logging_filters.ChannelFilter",
            "channel": "root",
        },
    },
    'handlers': {
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.json'), 
            'formatter': 'json',
            "filters": ["ch_session"],
        },
        'request': {
            'level': LOG_LEVEL,
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/request.json'),
            'formatter': 'json',
            "filters": ["ch_request"],
        },
        'admin': {
            'level': LOG_LEVEL,
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/admin.json'),
            'formatter': 'json',  
            "filters": ["ch_admin"],
        },
        'root': {
            'level': LOG_LEVEL,
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/root.json'),
            'formatter': 'json',
            "filters": ["ch_root"],
        },
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'json',
            "filters": ["ch_root"],
        },
    },
    'loggers': {
        'session-auth': {
            'handlers': ['file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'request': {
            'handlers': ['request'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'admin': {
            'handlers': ['admin'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'root': {
            'handlers': ['console', 'root'],
            'level': LOG_LEVEL,
        },
    },
}

if LOG_TO_STDOUT:

    for h_name in ("file", "request", "admin", "root"):
        LOGGING["handlers"][h_name]["class"] = "logging.StreamHandler"
        LOGGING["handlers"][h_name].pop("filename", None)

    LOGGING["root"] = {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    }

REDIS_URL = config("REDIS_URL", default="redis://redis:6379/1")

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'TIMEOUT': CACHE_TIMEOUT,
        'KEY_PREFIX': '',
    }
}
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
