# Generated by Django 5.2.2 on 2025-07-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='blocked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The time when address was block', verbose_name='Blocked At'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='endpoint',
            field=models.CharField(default='', editable=False, help_text='Path', max_length=255, verbose_name='Endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.GenericIPAddressField(editable=False, help_text='The unique blocked address IP', unique=True, verbose_name='Blocked Ip'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='is_temporary',
            field=models.BooleanField(default=True, help_text='if address is temporary block', verbose_name='Is Temporary'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='referer',
            field=models.CharField(editable=False, help_text='Referer', max_length=255, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='user_agent',
            field=models.CharField(editable=False, help_text='User Agent', max_length=255, verbose_name='User Agent'),
        ),
    ]
