# Generated by Django 5.2.2 on 2025-10-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedip',
            name='endpoint',
            field=models.CharField(editable=False, help_text='The path or endpoint that triggered the block.', max_length=255, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='is_temporary',
            field=models.BooleanField(default=True, help_text='Whether the block is temporary (vs permanent).', verbose_name='Is Temporary'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='referer',
            field=models.CharField(editable=False, help_text='HTTP referer header of the blocked request.', max_length=255, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='user_agent',
            field=models.CharField(editable=False, help_text='User agent string of the client that was blocked.', max_length=255, verbose_name='User Agent'),
        ),
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_dek_nonce', models.BinaryField(help_text='12-byte AES-GCM nonce used to wrap the DEK.', verbose_name='wrapped DEK nonce')),
                ('wrapped_dek_ct', models.BinaryField(help_text='Ciphertext (with GCM tag) of the DEK wrapped by the KEK.', verbose_name='wrapped DEK ciphertext')),
                ('wrapped_hmac_nonce', models.BinaryField(blank=True, help_text='12-byte AES-GCM nonce used to wrap the HMAC key.', null=True, verbose_name='wrapped HMAC nonce')),
                ('wrapped_hmac_ct', models.BinaryField(blank=True, help_text='Ciphertext (with GCM tag) of the HMAC key wrapped by the KEK.', null=True, verbose_name='wrapped HMAC ciphertext')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when Key was created', verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The time when Key was updated', verbose_name='Update_at')),
                ('user', models.OneToOneField(editable=False, help_text='The user who owns this key bundle.', on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
