# Generated by Django 5.2.2 on 2025-10-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_blockedip_endpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkeys',
            name='wrapped_hmac_ct',
        ),
        migrations.RemoveField(
            model_name='userkeys',
            name='wrapped_hmac_nonce',
        ),
    ]
