"""Update market table

Revision ID: 0c85408ada53
Revises: b0b80acc195a
Create Date: 2025-11-13 17:21:39.401080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c85408ada53'
down_revision: Union[str, Sequence[str], None] = 'b0b80acc195a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('country', sa.String(length=12), nullable=False))
    op.add_column('market', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'market', ['country'])
    op.create_unique_constraint(None, 'market', ['timezone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market', type_='unique')
    op.drop_constraint(None, 'market', type_='unique')
    op.drop_column('market', 'timezone')
    op.drop_column('market', 'country')
    # ### end Alembic commands ###
