"""Create InstrumentSyncState table

Revision ID: 22819fd61e4d
Revises: ca109509efd7
Create Date: 2026-01-28 15:10:45.828649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22819fd61e4d'
down_revision: Union[str, Sequence[str], None] = 'ca109509efd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_sync_state',
    sa.Column('daily_last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_last_attempt_end', sa.Date(), nullable=True),
    sa.Column('daily_last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_last_success_end', sa.Date(), nullable=True),
    sa.Column('daily_last_requested_url', sa.Text(), nullable=True),
    sa.Column('daily_last_fetched_rows', sa.Integer(), nullable=True),
    sa.Column('daily_last_upserted_rows', sa.Integer(), nullable=True),
    sa.Column('daily_last_error', sa.Text(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument_sync_state')
    # ### end Alembic commands ###
