"""Create tables

Revision ID: 613f083939ec
Revises: 
Create Date: 2025-11-08 18:34:38.103948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613f083939ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('mic', sa.String(length=4), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('shortname', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('ETF', 'STOCK', 'BOND', 'CURRENCY_PAIR', 'CRYPTO_ASSET', 'INDEX', 'REIT', name='instrument_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='instrument_status_enum'), nullable=False),
    sa.Column('historical_source', sa.String(length=64), nullable=True),
    sa.Column('popularity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mic', 'symbol', name='uq_directory_mic_symbol'),
    sa.UniqueConstraint('shortname'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_dir_symbol_shortname', 'instrument', ['symbol', 'shortname'], unique=False)
    op.create_index(op.f('ix_instrument_historical_source'), 'instrument', ['historical_source'], unique=False)
    op.create_index(op.f('ix_instrument_isin'), 'instrument', ['isin'], unique=False)
    op.create_index(op.f('ix_instrument_mic'), 'instrument', ['mic'], unique=False)
    op.create_index(op.f('ix_instrument_popularity'), 'instrument', ['popularity'], unique=False)
    op.create_table('candle_daily',
    sa.Column('date_quote', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trade_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('date_quote', 'instrument_id')
    )
    op.create_index(op.f('ix_candle_daily_date_quote'), 'candle_daily', ['date_quote'], unique=False)
    op.create_index('ix_cd_instr_date_quote', 'candle_daily', ['instrument_id', 'date_quote'], unique=False)
    op.create_table('quote_latest',
    sa.Column('last_price', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('change_pct', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('href', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_index(op.f('ix_quote_latest_href'), 'quote_latest', ['href'], unique=False)
    op.create_index(op.f('ix_quote_latest_provider'), 'quote_latest', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_latest_provider'), table_name='quote_latest')
    op.drop_index(op.f('ix_quote_latest_href'), table_name='quote_latest')
    op.drop_table('quote_latest')
    op.drop_index('ix_cd_instr_date_quote', table_name='candle_daily')
    op.drop_index(op.f('ix_candle_daily_date_quote'), table_name='candle_daily')
    op.drop_table('candle_daily')
    op.drop_index(op.f('ix_instrument_popularity'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_mic'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_isin'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_historical_source'), table_name='instrument')
    op.drop_index('ix_dir_symbol_shortname', table_name='instrument')
    op.drop_table('instrument')
    # ### end Alembic commands ###
