"""Mic Unique

Revision ID: a61f559681c7
Revises: 0c85408ada53
Create Date: 2025-11-13 17:30:22.271143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61f559681c7'
down_revision: Union[str, Sequence[str], None] = '0c85408ada53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_mic'), table_name='market')
    op.create_index(op.f('ix_market_mic'), 'market', ['mic'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_mic'), table_name='market')
    op.create_index(op.f('ix_market_mic'), 'market', ['mic'], unique=False)
    # ### end Alembic commands ###
