"""Create market table

Revision ID: b0b80acc195a
Revises: 613f083939ec
Create Date: 2025-11-13 17:05:17.034820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b80acc195a'
down_revision: Union[str, Sequence[str], None] = '613f083939ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mic', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_market_mic'), 'market', ['mic'], unique=False)
    op.add_column('instrument', sa.Column('market_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_instrument_mic'), table_name='instrument')
    op.drop_constraint(op.f('uq_directory_mic_symbol'), 'instrument', type_='unique')
    op.create_index(op.f('ix_instrument_market_id'), 'instrument', ['market_id'], unique=False)
    op.create_unique_constraint('uq_instrument_symbol', 'instrument', ['symbol'])
    op.create_foreign_key(None, 'instrument', 'market', ['market_id'], ['id'], ondelete='CASCADE')
    op.drop_column('instrument', 'mic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('mic', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'instrument', type_='foreignkey')
    op.drop_constraint('uq_instrument_symbol', 'instrument', type_='unique')
    op.drop_index(op.f('ix_instrument_market_id'), table_name='instrument')
    op.create_unique_constraint(op.f('uq_directory_mic_symbol'), 'instrument', ['mic', 'symbol'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_instrument_mic'), 'instrument', ['mic'], unique=False)
    op.drop_column('instrument', 'market_id')
    op.drop_index(op.f('ix_market_mic'), table_name='market')
    op.drop_table('market')
    # ### end Alembic commands ###
