"""Change country and TZ unigue

Revision ID: c7455a2394cf
Revises: a61f559681c7
Create Date: 2025-11-13 17:38:05.445064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7455a2394cf'
down_revision: Union[str, Sequence[str], None] = 'a61f559681c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('market_country_key'), 'market', type_='unique')
    op.drop_constraint(op.f('market_timezone_key'), 'market', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('market_timezone_key'), 'market', ['timezone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('market_country_key'), 'market', ['country'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
