"""changed wallet_note

Revision ID: 05f9070a11b6
Revises: 56ee8e6644c4
Create Date: 2025-12-21 11:09:06.737992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05f9070a11b6'
down_revision: Union[str, None] = '56ee8e6644c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_notes', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_wallet_notes_wallet_id'), table_name='wallet_notes')
    op.create_index(op.f('ix_wallet_notes_user_id'), 'wallet_notes', ['user_id'], unique=True)
    op.drop_constraint(op.f('wallet_notes_wallet_id_fkey'), 'wallet_notes', type_='foreignkey')
    op.create_foreign_key(None, 'wallet_notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('wallet_notes', 'wallet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_notes', sa.Column('wallet_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wallet_notes', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_notes_wallet_id_fkey'), 'wallet_notes', 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_wallet_notes_user_id'), table_name='wallet_notes')
    op.create_index(op.f('ix_wallet_notes_wallet_id'), 'wallet_notes', ['wallet_id'], unique=True)
    op.drop_column('wallet_notes', 'user_id')
    # ### end Alembic commands ###
