"""Create debt table

Revision ID: 2375a0e2a01c
Revises: 95226bc1b50f
Create Date: 2025-12-20 05:48:00.472458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2375a0e2a01c'
down_revision: Union[str, None] = '95226bc1b50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    currency_enum = postgresql.ENUM(
        "PLN", "USD", "EUR",
        name="currency_enum",
        create_type=False,
    )

    # create only if missing
    currency_enum.create(bind, checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('lander', sa.String(length=255), nullable=False),
        sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", currency_enum, nullable=False),
        sa.Column('interest_rate_pct', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
        sa.Column('monthly_payment', sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('wallet_id', sa.UUID(), nullable=False),
        sa.CheckConstraint('amount >= 0', name='ck_debt_amount_nonneg'),
        sa.CheckConstraint('char_length(btrim(lander)) > 0', name='ck_debt_lander_not_empty'),
        sa.CheckConstraint('char_length(btrim(name)) > 0', name='ck_debt_name_not_empty'),
        sa.CheckConstraint('interest_rate_pct >= 0', name='ck_debt_rate_nonneg'),
        sa.CheckConstraint('monthly_payment >= 0', name='ck_debt_payment_nonneg'),
        sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_wallet_id'), 'debt', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debt_wallet_id'), table_name='debt')
    op.drop_table('debt')
    # ### end Alembic commands ###
