"""Create brokerageEvent

Revision ID: 2db43869e26f
Revises: 9cd7ecb33b80
Create Date: 2025-10-26 16:16:16.358555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2db43869e26f'
down_revision: Union[str, None] = '9cd7ecb33b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokerage_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Enum('TRADE_BUY', 'TRADE_SELL', 'SPLIT', name='brokerage_event_kind'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('split_ratio', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('trade_at', sa.DateTime(), nullable=True),
    sa.Column('brokerage_account_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_brokevent_price_nonneg'),
    sa.CheckConstraint('quantity >= 0', name='ck_brokevent_quantity_nonneg'),
    sa.ForeignKeyConstraint(['brokerage_account_id'], ['brokerage_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokerage_events_brokerage_account_id'), 'brokerage_events', ['brokerage_account_id'], unique=False)
    op.create_index(op.f('ix_brokerage_events_instrument_id'), 'brokerage_events', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brokerage_events_instrument_id'), table_name='brokerage_events')
    op.drop_index(op.f('ix_brokerage_events_brokerage_account_id'), table_name='brokerage_events')
    op.drop_table('brokerage_events')
    # ### end Alembic commands ###
