"""Create recurring_expenses teble

Revision ID: 2ec445874d94
Revises: 2375a0e2a01c
Create Date: 2025-12-21 07:20:04.036854

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ec445874d94'
down_revision: Union[str, None] = '2375a0e2a01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    currency_enum = postgresql.ENUM(
        "PLN", "USD", "EUR",
        name="currency_enum",
        create_type=False,
    )

    # create only if missing
    currency_enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expenses',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column("currency", currency_enum, nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_recurring_exp_amount_nonneg'),
    sa.CheckConstraint('due_day >= 1 AND due_day <= 31', name='ck_recurring_exp_due_day_range'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_exp_wallet_due_day', 'recurring_expenses', ['wallet_id', 'due_day'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_wallet_id'), 'recurring_expenses', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_expenses_wallet_id'), table_name='recurring_expenses')
    op.drop_index('ix_recurring_exp_wallet_due_day', table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
