"""changed transactions table

Revision ID: 35341d54de44
Revises: 2df0f0a2eebb
Create Date: 2025-12-23 09:35:49.974678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35341d54de44'
down_revision: Union[str, None] = '2df0f0a2eebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###
