"""Create snapshot tables

Revision ID: 562511668b7c
Revises: 8e4122540d5b
Create Date: 2026-01-03 14:00:56.358916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '562511668b7c'
down_revision: Union[str, None] = '8e4122540d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    currency_enum = postgresql.ENUM(
        "PLN", "USD", "EUR",
        name="currency_enum",
        create_type=False,
    )

    # create only if missing
    currency_enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_monthly_snapshots',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('rates_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_key', name='uq_fx_month_key')
    )
    op.create_index('ix_fx_month_key', 'fx_monthly_snapshots', ['month_key'], unique=False)
    op.create_index(op.f('ix_fx_monthly_snapshots_month_key'), 'fx_monthly_snapshots', ['month_key'], unique=False)
    op.create_table('brokerage_account_monthly_snapshots',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column("currency", currency_enum, nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('stocks', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('brokerage_account_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['brokerage_account_id'], ['brokerage_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brokerage_account_id', 'month_key', name='uq_broacc_monthly_snapshot')
    )
    op.create_index('ix_broacc_monthly_wallet_month', 'brokerage_account_monthly_snapshots', ['wallet_id', 'month_key'], unique=False)
    op.create_index('ix_broacc_monthly_wallet_month_id', 'brokerage_account_monthly_snapshots', ['wallet_id', 'month_key', 'brokerage_account_id'], unique=False)
    op.create_index(op.f('ix_brokerage_account_monthly_snapshots_brokerage_account_id'), 'brokerage_account_monthly_snapshots', ['brokerage_account_id'], unique=False)
    op.create_index(op.f('ix_brokerage_account_monthly_snapshots_month_key'), 'brokerage_account_monthly_snapshots', ['month_key'], unique=False)
    op.create_index(op.f('ix_brokerage_account_monthly_snapshots_wallet_id'), 'brokerage_account_monthly_snapshots', ['wallet_id'], unique=False)
    op.create_table('deposit_account_monthly_snapshots',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column("currency", currency_enum, nullable=False),
    sa.Column('available', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['deposit_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'month_key', name='uq_depacc_monthly_snapshot')
    )
    op.create_index('ix_depacc_monthly_wallet_month', 'deposit_account_monthly_snapshots', ['wallet_id', 'month_key'], unique=False)
    op.create_index('ix_depacc_monthly_wallet_month_id', 'deposit_account_monthly_snapshots', ['wallet_id', 'month_key', 'account_id'], unique=False)
    op.create_index(op.f('ix_deposit_account_monthly_snapshots_account_id'), 'deposit_account_monthly_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_deposit_account_monthly_snapshots_month_key'), 'deposit_account_monthly_snapshots', ['month_key'], unique=False)
    op.create_index(op.f('ix_deposit_account_monthly_snapshots_wallet_id'), 'deposit_account_monthly_snapshots', ['wallet_id'], unique=False)
    op.create_table('metal_holding_monthly_snapshots',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column("currency", currency_enum, nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('metal_holding_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['metal_holding_id'], ['metal_holdings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal_holding_id', 'month_key', name='uq_metal_monthly_snapshot')
    )
    op.create_index(op.f('ix_metal_holding_monthly_snapshots_metal_holding_id'), 'metal_holding_monthly_snapshots', ['metal_holding_id'], unique=False)
    op.create_index(op.f('ix_metal_holding_monthly_snapshots_month_key'), 'metal_holding_monthly_snapshots', ['month_key'], unique=False)
    op.create_index(op.f('ix_metal_holding_monthly_snapshots_wallet_id'), 'metal_holding_monthly_snapshots', ['wallet_id'], unique=False)
    op.create_index('ix_metal_wallet_month', 'metal_holding_monthly_snapshots', ['wallet_id', 'month_key'], unique=False)
    op.create_index('ix_metal_wallet_month_id', 'metal_holding_monthly_snapshots', ['wallet_id', 'month_key', 'metal_holding_id'], unique=False)
    op.create_table('real_estate_monthly_snapshots',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column("currency", currency_enum, nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('real_estate_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['real_estate_id'], ['real_estates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_estate_id', 'month_key', name='uq_re_monthly_snapshot')
    )
    op.create_index('ix_re_monthly_wallet_month', 'real_estate_monthly_snapshots', ['wallet_id', 'month_key'], unique=False)
    op.create_index('ix_re_monthly_wallet_month_id', 'real_estate_monthly_snapshots', ['wallet_id', 'month_key', 'real_estate_id'], unique=False)
    op.create_index(op.f('ix_real_estate_monthly_snapshots_month_key'), 'real_estate_monthly_snapshots', ['month_key'], unique=False)
    op.create_index(op.f('ix_real_estate_monthly_snapshots_real_estate_id'), 'real_estate_monthly_snapshots', ['real_estate_id'], unique=False)
    op.create_index(op.f('ix_real_estate_monthly_snapshots_wallet_id'), 'real_estate_monthly_snapshots', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_real_estate_monthly_snapshots_wallet_id'), table_name='real_estate_monthly_snapshots')
    op.drop_index(op.f('ix_real_estate_monthly_snapshots_real_estate_id'), table_name='real_estate_monthly_snapshots')
    op.drop_index(op.f('ix_real_estate_monthly_snapshots_month_key'), table_name='real_estate_monthly_snapshots')
    op.drop_index('ix_re_monthly_wallet_month_id', table_name='real_estate_monthly_snapshots')
    op.drop_index('ix_re_monthly_wallet_month', table_name='real_estate_monthly_snapshots')
    op.drop_table('real_estate_monthly_snapshots')
    op.drop_index('ix_metal_wallet_month_id', table_name='metal_holding_monthly_snapshots')
    op.drop_index('ix_metal_wallet_month', table_name='metal_holding_monthly_snapshots')
    op.drop_index(op.f('ix_metal_holding_monthly_snapshots_wallet_id'), table_name='metal_holding_monthly_snapshots')
    op.drop_index(op.f('ix_metal_holding_monthly_snapshots_month_key'), table_name='metal_holding_monthly_snapshots')
    op.drop_index(op.f('ix_metal_holding_monthly_snapshots_metal_holding_id'), table_name='metal_holding_monthly_snapshots')
    op.drop_table('metal_holding_monthly_snapshots')
    op.drop_index(op.f('ix_deposit_account_monthly_snapshots_wallet_id'), table_name='deposit_account_monthly_snapshots')
    op.drop_index(op.f('ix_deposit_account_monthly_snapshots_month_key'), table_name='deposit_account_monthly_snapshots')
    op.drop_index(op.f('ix_deposit_account_monthly_snapshots_account_id'), table_name='deposit_account_monthly_snapshots')
    op.drop_index('ix_depacc_monthly_wallet_month_id', table_name='deposit_account_monthly_snapshots')
    op.drop_index('ix_depacc_monthly_wallet_month', table_name='deposit_account_monthly_snapshots')
    op.drop_table('deposit_account_monthly_snapshots')
    op.drop_index(op.f('ix_brokerage_account_monthly_snapshots_wallet_id'), table_name='brokerage_account_monthly_snapshots')
    op.drop_index(op.f('ix_brokerage_account_monthly_snapshots_month_key'), table_name='brokerage_account_monthly_snapshots')
    op.drop_index(op.f('ix_brokerage_account_monthly_snapshots_brokerage_account_id'), table_name='brokerage_account_monthly_snapshots')
    op.drop_index('ix_broacc_monthly_wallet_month_id', table_name='brokerage_account_monthly_snapshots')
    op.drop_index('ix_broacc_monthly_wallet_month', table_name='brokerage_account_monthly_snapshots')
    op.drop_table('brokerage_account_monthly_snapshots')
    op.drop_index(op.f('ix_fx_monthly_snapshots_month_key'), table_name='fx_monthly_snapshots')
    op.drop_index('ix_fx_month_key', table_name='fx_monthly_snapshots')
    op.drop_table('fx_monthly_snapshots')
    # ### end Alembic commands ###
