"""create tables

Revision ID: 6b3fd95090ac
Revises: 5fadfac6dcc5
Create Date: 2025-08-18 17:11:39.209903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b3fd95090ac'
down_revision: Union[str, None] = '5fadfac6dcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shortname', sa.String(length=5), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('shortname')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('STOCK', 'ETF', 'BOND', 'FUND', 'CRYPTO', name='instrument_type_enum'), nullable=False),
    sa.Column('currency', sa.Enum('PLN', 'USD', 'EUR', name='currency_enum'), nullable=False),
    sa.Column('sync_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instr_ref_symbol', 'instruments', ['symbol'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wallets',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_wallet_owner_name')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('brokerage_accounts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'bank_id', 'name', name='uq_brokerage_name_per_wallet_bank')
    )
    op.create_index(op.f('ix_brokerage_accounts_bank_id'), 'brokerage_accounts', ['bank_id'], unique=False)
    op.create_index(op.f('ix_brokerage_accounts_wallet_id'), 'brokerage_accounts', ['wallet_id'], unique=False)
    op.create_index('ix_brokerage_wallet_bank', 'brokerage_accounts', ['wallet_id', 'bank_id'], unique=False)
    op.create_table('deposit_accounts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('CURRENT', 'SAVINGS', 'BROKERAGE', 'CREDIT', name='account_type_enum'), nullable=False),
    sa.Column('account_number_enc', sa.LargeBinary(), nullable=False),
    sa.Column('account_number_fp', sa.LargeBinary(length=32), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('currency', sa.Enum('PLN', 'USD', 'EUR', name='currency_enum'), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban'),
    sa.UniqueConstraint('wallet_id', 'name', name='uq_depacc_wallet_name')
    )
    op.create_index(op.f('ix_deposit_accounts_account_number_fp'), 'deposit_accounts', ['account_number_fp'], unique=True)
    op.create_index(op.f('ix_deposit_accounts_bank_id'), 'deposit_accounts', ['bank_id'], unique=False)
    op.create_index(op.f('ix_deposit_accounts_wallet_id'), 'deposit_accounts', ['wallet_id'], unique=False)
    op.create_table('metal_holdings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metal', sa.Enum('GOLD', 'SILVER', 'PLATINUM', 'PALLADIUM', name='metal_enum'), nullable=False),
    sa.Column('grams', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cost_currency', sa.Enum('PLN', 'USD', 'EUR', name='currency_enum'), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'metal', name='uq_wallet_metal_one_row')
    )
    op.create_index(op.f('ix_metal_holdings_wallet_id'), 'metal_holdings', ['wallet_id'], unique=False)
    op.create_table('real_estates',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('APARTMENT', 'LAND', 'HAUSE', name='propertyt_type_enum'), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('purchase_currency', sa.Enum('PLN', 'USD', 'EUR', name='currency_enum'), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estates_wallet_id'), 'real_estates', ['wallet_id'], unique=False)
    op.create_table('brokerage_deposit_links',
    sa.Column('brokerage_account_id', sa.UUID(), nullable=False),
    sa.Column('deposit_account_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.Enum('PLN', 'USD', 'EUR', name='currency_enum'), nullable=False),
    sa.ForeignKeyConstraint(['brokerage_account_id'], ['brokerage_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deposit_account_id'], ['deposit_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('brokerage_account_id', 'deposit_account_id'),
    sa.UniqueConstraint('brokerage_account_id', 'currency', name='uq_brokerage_currency_one_deposit')
    )
    op.create_table('deposit_account_balances',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('available', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('blocked', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['deposit_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('holdings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), server_default='0', nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'instrument_id', name='uq_holding')
    )
    op.create_index(op.f('ix_holdings_account_id'), 'holdings', ['account_id'], unique=False)
    op.create_index(op.f('ix_holdings_instrument_id'), 'holdings', ['instrument_id'], unique=False)
    op.create_table('transactions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('INTERNAL', 'EXTERNAL', name='transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('balance_before', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['deposit_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_holdings_instrument_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_account_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_table('deposit_account_balances')
    op.drop_table('brokerage_deposit_links')
    op.drop_index(op.f('ix_real_estates_wallet_id'), table_name='real_estates')
    op.drop_table('real_estates')
    op.drop_index(op.f('ix_metal_holdings_wallet_id'), table_name='metal_holdings')
    op.drop_table('metal_holdings')
    op.drop_index(op.f('ix_deposit_accounts_wallet_id'), table_name='deposit_accounts')
    op.drop_index(op.f('ix_deposit_accounts_bank_id'), table_name='deposit_accounts')
    op.drop_index(op.f('ix_deposit_accounts_account_number_fp'), table_name='deposit_accounts')
    op.drop_table('deposit_accounts')
    op.drop_index('ix_brokerage_wallet_bank', table_name='brokerage_accounts')
    op.drop_index(op.f('ix_brokerage_accounts_wallet_id'), table_name='brokerage_accounts')
    op.drop_index(op.f('ix_brokerage_accounts_bank_id'), table_name='brokerage_accounts')
    op.drop_table('brokerage_accounts')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index('ix_instr_ref_symbol', table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('banks')
    # ### end Alembic commands ###
