"""created goal table

Revision ID: 8e4122540d5b
Revises: a24f6f732f41
Create Date: 2025-12-28 09:43:14.847808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e4122540d5b'
down_revision: Union[str, None] = 'a24f6f732f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    currency_enum = postgresql.ENUM(
        "PLN", "USD", "EUR",
        name="currency_enum",
        create_type=False,
    )

    # create only if missing
    currency_enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('year_goals',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rev_target_year', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('exp_budget_year', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column("currency", currency_enum, nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('year >= 1970 AND year <= 2100', name='ck_year_goals_year_range'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'year', name='uq_year_goals_wallet_year')
    )
    op.create_index(op.f('ix_year_goals_wallet_id'), 'year_goals', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_year_goals_year'), 'year_goals', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_year_goals_year'), table_name='year_goals')
    op.drop_index(op.f('ix_year_goals_wallet_id'), table_name='year_goals')
    op.drop_table('year_goals')
    # ### end Alembic commands ###
