"""added quote_symbol tp MetalHolding

Revision ID: 95226bc1b50f
Revises: 2272f78fdbca
Create Date: 2025-12-19 12:33:14.483883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95226bc1b50f'
down_revision: Union[str, None] = '2272f78fdbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metal_holdings', sa.Column('quote_symbol', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_metal_holdings_quote_symbol'), 'metal_holdings', ['quote_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metal_holdings_quote_symbol'), table_name='metal_holdings')
    op.drop_column('metal_holdings', 'quote_symbol')
    # ### end Alembic commands ###
