"""change_transaction_table_1

Revision ID: 9cd7ecb33b80
Revises: 507f4d0cfe00
Create Date: 2025-10-14 17:29:01.740902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9cd7ecb33b80'
down_revision: Union[str, None] = '507f4d0cfe00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date_transaction', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'date_transaction')
    # ### end Alembic commands ###
