"""Create favorite alert tables

Revision ID: a06aa6f90230
Revises: f012b0da198d
Create Date: 2026-01-24 05:02:23.530300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a06aa6f90230'
down_revision: Union[str, None] = 'f012b0da198d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_lists',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_fav_list_user_name')
    )
    op.create_index('ix_fav_list_user_id', 'favorite_lists', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorite_lists_user_id'), 'favorite_lists', ['user_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('below_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('above_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('one_shot', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(below_price IS NULL OR below_price >= 0) AND (above_price IS NULL OR above_price >= 0)', name='ck_alert_prices_nonneg'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instrument_id', name='uq_alert_user_instr')
    )
    op.create_index('ix_alert_user_instr', 'price_alerts', ['user_id', 'instrument_id'], unique=False)
    op.create_index(op.f('ix_price_alerts_instrument_id'), 'price_alerts', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    op.create_table('favorite_items',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('favorite_list_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_list_id'], ['favorite_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('favorite_list_id', 'instrument_id', name='uq_fav_item_unique')
    )
    op.create_index('ix_fav_item_list_instr', 'favorite_items', ['favorite_list_id', 'instrument_id'], unique=False)
    op.create_index(op.f('ix_favorite_items_favorite_list_id'), 'favorite_items', ['favorite_list_id'], unique=False)
    op.create_index(op.f('ix_favorite_items_instrument_id'), 'favorite_items', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_items_instrument_id'), table_name='favorite_items')
    op.drop_index(op.f('ix_favorite_items_favorite_list_id'), table_name='favorite_items')
    op.drop_index('ix_fav_item_list_instr', table_name='favorite_items')
    op.drop_table('favorite_items')
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_instrument_id'), table_name='price_alerts')
    op.drop_index('ix_alert_user_instr', table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_favorite_lists_user_id'), table_name='favorite_lists')
    op.drop_index('ix_fav_list_user_id', table_name='favorite_lists')
    op.drop_table('favorite_lists')
    # ### end Alembic commands ###
