"""add metal and real estate capital gain kinds

Revision ID: a24f6f732f41
Revises: 35341d54de44
Create Date: 2025-12-25 17:30:01.767668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a24f6f732f41'
down_revision: Union[str, None] = '35341d54de44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE capital_gain_kind_enum ADD VALUE IF NOT EXISTS 'METAL_REALIZED_PNL'")
        op.execute("ALTER TYPE capital_gain_kind_enum ADD VALUE IF NOT EXISTS 'REAL_ESTATE_REALIZED_PNL'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
