"""encrypt IBAN: add iban_enc & iban_fp

Revision ID: af44dee27938
Revises: 2b793eafa658
Create Date: 2025-10-02 09:53:08.006372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af44dee27938'
down_revision: Union[str, None] = '2b793eafa658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_accounts', sa.Column('iban_enc', sa.LargeBinary(), nullable=True))
    op.add_column('deposit_accounts', sa.Column('iban_fp', sa.LargeBinary(length=32), nullable=True))
    op.drop_constraint(op.f('deposit_accounts_iban_key'), 'deposit_accounts', type_='unique')
    op.create_index(op.f('ix_deposit_accounts_iban_fp'), 'deposit_accounts', ['iban_fp'], unique=True)
    op.drop_column('deposit_accounts', 'iban')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_accounts', sa.Column('iban', sa.VARCHAR(length=34), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_deposit_accounts_iban_fp'), table_name='deposit_accounts')
    op.create_unique_constraint(op.f('deposit_accounts_iban_key'), 'deposit_accounts', ['iban'], postgresql_nulls_not_distinct=False)
    op.drop_column('deposit_accounts', 'iban_fp')
    op.drop_column('deposit_accounts', 'iban_enc')
    # ### end Alembic commands ###
