"""change account_number_enc and iban_enc

Revision ID: b5b0e9bacc49
Revises: af44dee27938
Create Date: 2025-10-02 13:07:12.538504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5b0e9bacc49'
down_revision: Union[str, None] = 'af44dee27938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_accounts', sa.Column('account_number_nonce', sa.LargeBinary(length=12), nullable=False))
    op.add_column('deposit_accounts', sa.Column('account_number_ct', sa.LargeBinary(), nullable=False))
    op.add_column('deposit_accounts', sa.Column('iban_nonce', sa.LargeBinary(length=12), nullable=True))
    op.add_column('deposit_accounts', sa.Column('iban_ct', sa.LargeBinary(), nullable=True))
    op.drop_column('deposit_accounts', 'account_number_enc')
    op.drop_column('deposit_accounts', 'iban_enc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_accounts', sa.Column('iban_enc', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('deposit_accounts', sa.Column('account_number_enc', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('deposit_accounts', 'iban_ct')
    op.drop_column('deposit_accounts', 'iban_nonce')
    op.drop_column('deposit_accounts', 'account_number_ct')
    op.drop_column('deposit_accounts', 'account_number_nonce')
    # ### end Alembic commands ###
