"""Create capital gain table

Revision ID: b8938a94bf1e
Revises: 5466688f1268
Create Date: 2025-11-22 15:27:38.481455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import UserDefinedType


# revision identifiers, used by Alembic.
revision: str = 'b8938a94bf1e'
down_revision: Union[str, None] = '5466688f1268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

class CurrencyEnumType(UserDefinedType):
    """Use existing PostgreSQL type `currency_enum` without trying to create it."""

    def get_col_spec(self, **kw):
        return "currency_enum"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capital_gains",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "DEPOSIT_INTEREST",
                "BROKER_REALIZED_PNL",
                "BROKER_DIVIDEND",
                name="capital_gain_kind_enum",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),

        sa.Column("currency", CurrencyEnumType(), nullable=False),

        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deposit_account_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deposit_account_id"],
            ["deposit_accounts.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capital_gains_deposit_account_id"),
        "capital_gains",
        ["deposit_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capital_gains_occurred_at"),
        "capital_gains",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capital_gains_transaction_id"),
        "capital_gains",
        ["transaction_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_capital_gains_transaction_id"),
        table_name="capital_gains",
    )
    op.drop_index(
        op.f("ix_capital_gains_occurred_at"),
        table_name="capital_gains",
    )
    op.drop_index(
        op.f("ix_capital_gains_deposit_account_id"),
        table_name="capital_gains",
    )
    op.drop_table("capital_gains")
    bind = op.get_bind()
    sa.Enum(name="capital_gain_kind_enum").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
