""" update wallet table

Revision ID: f012b0da198d
Revises: 562511668b7c
Create Date: 2026-01-04 09:29:27.647816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f012b0da198d'
down_revision: Union[str, None] = '562511668b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    currency_enum = postgresql.ENUM(
        "PLN", "USD", "EUR",
        name="currency_enum",
        create_type=False,
    )

    # create only if missing
    currency_enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column("currency", currency_enum, nullable=True))
    op.create_index(op.f('ix_wallets_currency'), 'wallets', ['currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_currency'), table_name='wallets')
    op.drop_column('wallets', 'currency')
    # ### end Alembic commands ###
