"""added table args

Revision ID: f07f22df507d
Revises: 6b3fd95090ac
Create Date: 2025-08-19 06:28:20.381421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f07f22df507d'
down_revision: Union[str, None] = '6b3fd95090ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments', 'symbol',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments', 'symbol',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
